# Generated by Django 2.2 on 2019-04-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_auto_20190414_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('sid', models.IntegerField(max_length=80)),
                ('age', models.IntegerField(max_length=80)),
                ('studyLevel', models.CharField(max_length=80)),
            ],
        ),
        migrations.DeleteModel(
            name='language',
        ),
    ]
